### ISSUE TITLE
Please update and make it easier too please

### ISSUE THREAD

**Issue by fisforfaheem** [maheshmnj/passwordfield-flutter-package#8]

**Comment by maheshj01** [comment]
@fisforfaheem  could you please describe the bug?

**Comment by fisforfaheem** [comment]
Bro Please do a video explaing how to add this to out form fields also tell how to edit the validators to work with emails and other fields etc...suppose we want to add similar thing to email. how to implement

**Comment by maheshj01** [comment]
@fisforfaheem password field doesn't work for email fields because it isn't designed for that, If you want to use validators  for an emailfield please take a look at the example here in the docs https://flutter.dev/docs/cookbook/forms/validation
for a video explanation please take a look at this https://www.youtube.com/watch?v=2rn3XbBijy4

**Comment by fisforfaheem** [comment]
Thanks, I'll check it out. I really love your extension and liked it,
Please make more and more



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/07/21,
08:45:07 PM

**Comment by maheshj01** [comment]
Closing this issue as invalid, If you see any further bugs or have a feature request for passwordfield widget feel free to file a new issue.
